- name: 'Provision wordpress'
  hosts: localhost
  become: true

  tasks:
    - name: Install prerequisites
      apt: name=aptitude update_cache=yes state=latest force_apt_get=yes
      tags: [ system ]

    - name: Install Packages
      apt:
        pkg:
          - apache2
          - php
          - php-mysql
          - libapache2-mod-php
        state: present
      tags: [ system ]

    - name: Install PHP Extensions
      apt:
        pkg:      
          - php-curl 
          - php-gd
          - php-mbstring 
          - php-xml
          - php-xmlrpc
          - php-soap
          - php-intl
          - php-zip
        state: present
      tags: [ system ]

  # Apache Configuration

    - name: Remove default index.html
      file:
        path: "/var/www/html/index.html"
        state: absent
      tags: [ apache ]

    - name: Set up Apache VirtualHost
      template:
        src: "/tmp/apache2.conf.j2"
        dest: "/etc/apache2/apache2.conf"
        force: yes
      notify: Reload Apache
      tags: [ apache ] 
    
  # WordPress Configuration
  
    - name: Download and unpack latest WordPress
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: "/var/www/html"
        remote_src: yes
      tags: [ wordpress ]

    - name: Move files
      shell: "/bin/mv /var/www/html/wordpress/* /var/www/html/"
      tags: [ wordpress ]

    - name: Remove wordpress directory
      file:
        path: "/var/www/html/wordpress"
        state: absent
      tags: [ wordpress ]

    - name: Set ownership
      file:
        path: "/var/www/html"
        state: directory
        recurse: yes
        owner: www-data
        group: www-data
      tags: [ wordpress ]

    - name: Set up wp-config
      template:
        src: "/tmp/wp-config.php.j2"
        dest: "/var/www/html/wp-config.php"
      tags: [ wordpress ]

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

    - name: Restart Apache
      service:
        name: apache2
        state: restarted